# coding: utf-8

"""
    TBA III

    Diese API ermöglicht den Zugriff auf Auswertungsdaten von VERA. Sie bietet Endpunkte für die Abfrage von Leistungsdaten auf verschiedenen Ebenen (Lerngruppe, Schule, Bundesland) und für verschiedene Arten von Daten (Kompetenzstufen, Item-Statistiken, Aggregationen).

    The version of the OpenAPI document: 1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
from inspect import getfullargspec
import json
import pprint
import re  # noqa: F401



from pydantic import BaseModel, ConfigDict, Field, StrictStr, ValidationError, field_validator
from typing import Any, List, Optional
from api.models.gender_characteristic import GenderCharacteristic
from api.models.language_at_home_characteristic import LanguageAtHomeCharacteristic
from api.models.other_characteristic import OtherCharacteristic
from typing import Union, Any, List, TYPE_CHECKING, Optional, Dict
from typing_extensions import Literal
from pydantic import StrictStr, Field
try:
    from typing import Self
except ImportError:
    from typing_extensions import Self

CHARACTERISTIC_ONE_OF_SCHEMAS = ["GenderCharacteristic", "LanguageAtHomeCharacteristic", "OtherCharacteristic"]

class Characteristic(BaseModel):
    """
    Characteristic
    """
    # data type: LanguageAtHomeCharacteristic
    oneof_schema_1_validator: Optional[LanguageAtHomeCharacteristic] = None
    # data type: GenderCharacteristic
    oneof_schema_2_validator: Optional[GenderCharacteristic] = None
    # data type: OtherCharacteristic
    oneof_schema_3_validator: Optional[OtherCharacteristic] = None
    actual_instance: Optional[Union[GenderCharacteristic, LanguageAtHomeCharacteristic, OtherCharacteristic]] = None
    one_of_schemas: List[str] = Literal["GenderCharacteristic", "LanguageAtHomeCharacteristic", "OtherCharacteristic"]

    model_config = {
        "validate_assignment": True,
        "protected_namespaces": (),
    }


    discriminator_value_class_map: Dict[str, str] = {
    }

    def __init__(self, *args, **kwargs) -> None:
        if args:
            if len(args) > 1:
                raise ValueError("If a position argument is used, only 1 is allowed to set `actual_instance`")
            if kwargs:
                raise ValueError("If a position argument is used, keyword arguments cannot be used.")
            super().__init__(actual_instance=args[0])
        else:
            super().__init__(**kwargs)

    @field_validator('actual_instance')
    def actual_instance_must_validate_oneof(cls, v):
        instance = Characteristic.model_construct()
        error_messages = []
        match = 0
        # validate data type: LanguageAtHomeCharacteristic
        if not isinstance(v, LanguageAtHomeCharacteristic):
            error_messages.append(f"Error! Input type `{type(v)}` is not `LanguageAtHomeCharacteristic`")
        else:
            match += 1
        # validate data type: GenderCharacteristic
        if not isinstance(v, GenderCharacteristic):
            error_messages.append(f"Error! Input type `{type(v)}` is not `GenderCharacteristic`")
        else:
            match += 1
        # validate data type: OtherCharacteristic
        if not isinstance(v, OtherCharacteristic):
            error_messages.append(f"Error! Input type `{type(v)}` is not `OtherCharacteristic`")
        else:
            match += 1
        if match > 1:
            # more than 1 match
            raise ValueError("Multiple matches found when setting `actual_instance` in Characteristic with oneOf schemas: GenderCharacteristic, LanguageAtHomeCharacteristic, OtherCharacteristic. Details: " + ", ".join(error_messages))
        elif match == 0:
            # no match
            raise ValueError("No match found when setting `actual_instance` in Characteristic with oneOf schemas: GenderCharacteristic, LanguageAtHomeCharacteristic, OtherCharacteristic. Details: " + ", ".join(error_messages))
        else:
            return v

    @classmethod
    def from_dict(cls, obj: dict) -> Self:
        return cls.from_json(json.dumps(obj))

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Returns the object represented by the json string"""
        instance = cls.model_construct()
        error_messages = []
        match = 0

        # deserialize data into LanguageAtHomeCharacteristic
        try:
            instance.actual_instance = LanguageAtHomeCharacteristic.from_json(json_str)
            match += 1
        except (ValidationError, ValueError) as e:
            error_messages.append(str(e))
        # deserialize data into GenderCharacteristic
        try:
            instance.actual_instance = GenderCharacteristic.from_json(json_str)
            match += 1
        except (ValidationError, ValueError) as e:
            error_messages.append(str(e))
        # deserialize data into OtherCharacteristic
        try:
            instance.actual_instance = OtherCharacteristic.from_json(json_str)
            match += 1
        except (ValidationError, ValueError) as e:
            error_messages.append(str(e))

        if match > 1:
            # more than 1 match
            raise ValueError("Multiple matches found when deserializing the JSON string into Characteristic with oneOf schemas: GenderCharacteristic, LanguageAtHomeCharacteristic, OtherCharacteristic. Details: " + ", ".join(error_messages))
        elif match == 0:
            # no match
            raise ValueError("No match found when deserializing the JSON string into Characteristic with oneOf schemas: GenderCharacteristic, LanguageAtHomeCharacteristic, OtherCharacteristic. Details: " + ", ".join(error_messages))
        else:
            return instance

    def to_json(self) -> str:
        """Returns the JSON representation of the actual instance"""
        if self.actual_instance is None:
            return "null"

        to_json = getattr(self.actual_instance, "to_json", None)
        if callable(to_json):
            return self.actual_instance.to_json()
        else:
            return json.dumps(self.actual_instance)

    def to_dict(self) -> Dict:
        """Returns the dict representation of the actual instance"""
        if self.actual_instance is None:
            return None

        to_dict = getattr(self.actual_instance, "to_dict", None)
        if callable(to_dict):
            return self.actual_instance.to_dict()
        else:
            # primitive type
            return self.actual_instance

    def to_str(self) -> str:
        """Returns the string representation of the actual instance"""
        return pprint.pformat(self.model_dump())


