# coding: utf-8

"""
    TBA III

    Diese API ermöglicht den Zugriff auf Auswertungsdaten von VERA. Sie bietet Endpunkte für die Abfrage von Leistungsdaten auf verschiedenen Ebenen (Lerngruppe, Schule, Bundesland) und für verschiedene Arten von Daten (Kompetenzstufen, Item-Statistiken, Aggregationen).

    The version of the OpenAPI document: 1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json




from pydantic import BaseModel, ConfigDict, Field, StrictFloat, StrictInt
from typing import Any, ClassVar, Dict, List, Optional, Union
from typing_extensions import Annotated
try:
    from typing import Self
except ImportError:
    from typing_extensions import Self

class DescriptiveStatistics(BaseModel):
    """
    DescriptiveStatistics
    """ # noqa: E501
    total: Optional[StrictInt] = Field(default=None, description="Gesamtzahl der Items")
    mean: Optional[Union[Annotated[float, Field(le=1, strict=True, ge=0)], Annotated[int, Field(le=1, strict=True, ge=0)]]] = Field(default=None, description="Anteil richtig gelöster Items / Mittlere Lösungsquote")
    frequency: Optional[StrictInt] = Field(default=None, description="Absolute Anzahl richtig gelöster Items")
    standard_deviation: Optional[Union[StrictFloat, StrictInt]] = Field(default=None, description="Standardabweichung der mittleren Lösungsquote", alias="standardDeviation")
    __properties: ClassVar[List[str]] = ["total", "mean", "frequency", "standardDeviation"]

    model_config = {
        "populate_by_name": True,
        "validate_assignment": True,
        "protected_namespaces": (),
    }


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Create an instance of DescriptiveStatistics from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        _dict = self.model_dump(
            by_alias=True,
            exclude={
            },
            exclude_none=True,
        )
        return _dict

    @classmethod
    def from_dict(cls, obj: Dict) -> Self:
        """Create an instance of DescriptiveStatistics from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "total": obj.get("total"),
            "mean": obj.get("mean"),
            "frequency": obj.get("frequency"),
            "standardDeviation": obj.get("standardDeviation")
        })
        return _obj


