# coding: utf-8

"""
    TBA III

    Diese API ermöglicht den Zugriff auf Auswertungsdaten von VERA. Sie bietet Endpunkte für die Abfrage von Leistungsdaten auf verschiedenen Ebenen (Lerngruppe, Schule, Bundesland) und für verschiedene Arten von Daten (Kompetenzstufen, Item-Statistiken, Aggregationen).

    The version of the OpenAPI document: 1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json




from pydantic import BaseModel, ConfigDict, Field, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from api.models.characteristic import Characteristic
from api.models.domain import Domain
from api.models.inline_object_inner_all_of_competence_levels_inner import InlineObjectInnerAllOfCompetenceLevelsInner
from api.models.value_group_attributes_inner import ValueGroupAttributesInner
try:
    from typing import Self
except ImportError:
    from typing_extensions import Self

class InlineObjectInner(BaseModel):
    """
    InlineObjectInner
    """ # noqa: E501
    id: Optional[StrictStr] = None
    name: StrictStr = Field(description="Bezeichnung der Wertegruppe")
    domain: Optional[Domain] = Field(default=None, description="Domäne der Wertegruppe (optional)")
    covariates: Optional[List[Characteristic]] = Field(default=None, description="Kovariaten der Testgruppe")
    attributes: Optional[List[ValueGroupAttributesInner]] = Field(default=None, description="Liste von Key-Value-Werten mit zusätzlichen Informationen")
    competence_levels: List[InlineObjectInnerAllOfCompetenceLevelsInner] = Field(description="Kompetenzstufenverteilung in der Wertegruppe", alias="competenceLevels")
    __properties: ClassVar[List[str]] = ["id", "name", "domain", "covariates", "attributes", "competenceLevels"]

    model_config = {
        "populate_by_name": True,
        "validate_assignment": True,
        "protected_namespaces": (),
    }


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Create an instance of InlineObjectInner from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        _dict = self.model_dump(
            by_alias=True,
            exclude={
            },
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of domain
        if self.domain:
            _dict['domain'] = self.domain.to_dict()
        # override the default output from pydantic by calling `to_dict()` of each item in covariates (list)
        _items = []
        if self.covariates:
            for _item in self.covariates:
                if _item:
                    _items.append(_item.to_dict())
            _dict['covariates'] = _items
        # override the default output from pydantic by calling `to_dict()` of each item in attributes (list)
        _items = []
        if self.attributes:
            for _item in self.attributes:
                if _item:
                    _items.append(_item.to_dict())
            _dict['attributes'] = _items
        # override the default output from pydantic by calling `to_dict()` of each item in competence_levels (list)
        _items = []
        if self.competence_levels:
            for _item in self.competence_levels:
                if _item:
                    _items.append(_item.to_dict())
            _dict['competenceLevels'] = _items
        return _dict

    @classmethod
    def from_dict(cls, obj: Dict) -> Self:
        """Create an instance of InlineObjectInner from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "id": obj.get("id"),
            "name": obj.get("name"),
            "domain": Domain.from_dict(obj.get("domain")) if obj.get("domain") is not None else None,
            "covariates": [Characteristic.from_dict(_item) for _item in obj.get("covariates")] if obj.get("covariates") is not None else None,
            "attributes": [ValueGroupAttributesInner.from_dict(_item) for _item in obj.get("attributes")] if obj.get("attributes") is not None else None,
            "competenceLevels": [InlineObjectInnerAllOfCompetenceLevelsInner.from_dict(_item) for _item in obj.get("competenceLevels")] if obj.get("competenceLevels") is not None else None
        })
        return _obj


