# coding: utf-8

"""
    TBA III

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.3
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json




from pydantic import BaseModel, ConfigDict, Field, StrictStr, field_validator
from typing import Any, ClassVar, Dict, List, Optional
from api.models.descriptive_statistics import DescriptiveStatistics
try:
    from typing import Self
except ImportError:
    from typing_extensions import Self

class InlineObjectInner2AllOfAggregationsInner(BaseModel):
    """
    InlineObjectInner2AllOfAggregationsInner
    """ # noqa: E501
    type: Optional[StrictStr] = Field(default=None, description="Aggregationsart (z.B. Kompetenzstandard, Aufgabe), eigene Aggregationsarten können definiert werden.")
    value: Optional[StrictStr] = Field(default=None, description="Einzelne aggregierte Gruppe, z.B. \"Leseverstehen\" und \"Orthografie\" bei Domänen.")
    descriptive_statistics: Optional[DescriptiveStatistics] = Field(default=None, alias="descriptiveStatistics")
    included_iqb_ids: Optional[List[StrictStr]] = Field(default=None, description="Liste von IQB ItemIds, die in der Berechnung der Aggregation berücksichtigt wurden.", alias="includedIqbIds")
    __properties: ClassVar[List[str]] = ["type", "value", "descriptiveStatistics", "includedIqbIds"]

    @field_validator('type')
    def type_validate_enum(cls, value):
        """Validates the enum"""
        if value is None:
            return value

        if value not in ('competenceStandard', 'custom',):
            raise ValueError("must be one of enum values ('competenceStandard', 'custom')")
        return value

    model_config = {
        "populate_by_name": True,
        "validate_assignment": True,
        "protected_namespaces": (),
    }


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Create an instance of InlineObjectInner2AllOfAggregationsInner from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        _dict = self.model_dump(
            by_alias=True,
            exclude={
            },
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of descriptive_statistics
        if self.descriptive_statistics:
            _dict['descriptiveStatistics'] = self.descriptive_statistics.to_dict()
        return _dict

    @classmethod
    def from_dict(cls, obj: Dict) -> Self:
        """Create an instance of InlineObjectInner2AllOfAggregationsInner from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "type": obj.get("type"),
            "value": obj.get("value"),
            "descriptiveStatistics": DescriptiveStatistics.from_dict(obj.get("descriptiveStatistics")) if obj.get("descriptiveStatistics") is not None else None,
            "includedIqbIds": obj.get("includedIqbIds")
        })
        return _obj


