# coding: utf-8

"""
    TBA III

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.3
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json




from pydantic import BaseModel, ConfigDict, Field, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from api.models.comparison_inner import ComparisonInner
from api.models.descriptive_statistics import DescriptiveStatistics
from api.models.item_parameters import ItemParameters
try:
    from typing import Self
except ImportError:
    from typing_extensions import Self

class ItemStatisticsInner(BaseModel):
    """
    ItemStatisticsInner
    """ # noqa: E501
    id: Optional[StrictStr] = None
    name: StrictStr = Field(description="Bezeichnung des Items im Testheft")
    iqb_id: StrictStr = Field(description="IQB Item-Id des Items", alias="iqbId")
    parameters: Optional[ItemParameters] = None
    descriptive_statistics: Optional[DescriptiveStatistics] = Field(default=None, alias="descriptiveStatistics")
    comparison: Optional[List[ComparisonInner]] = Field(default=None, description="Vergleichswerte mit Vergleichsgruppen")
    __properties: ClassVar[List[str]] = ["id", "name", "iqbId", "parameters", "descriptiveStatistics", "comparison"]

    model_config = {
        "populate_by_name": True,
        "validate_assignment": True,
        "protected_namespaces": (),
    }


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Create an instance of ItemStatisticsInner from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        _dict = self.model_dump(
            by_alias=True,
            exclude={
            },
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of parameters
        if self.parameters:
            _dict['parameters'] = self.parameters.to_dict()
        # override the default output from pydantic by calling `to_dict()` of descriptive_statistics
        if self.descriptive_statistics:
            _dict['descriptiveStatistics'] = self.descriptive_statistics.to_dict()
        # override the default output from pydantic by calling `to_dict()` of each item in comparison (list)
        _items = []
        if self.comparison:
            for _item in self.comparison:
                if _item:
                    _items.append(_item.to_dict())
            _dict['comparison'] = _items
        return _dict

    @classmethod
    def from_dict(cls, obj: Dict) -> Self:
        """Create an instance of ItemStatisticsInner from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "id": obj.get("id"),
            "name": obj.get("name"),
            "iqbId": obj.get("iqbId"),
            "parameters": ItemParameters.from_dict(obj.get("parameters")) if obj.get("parameters") is not None else None,
            "descriptiveStatistics": DescriptiveStatistics.from_dict(obj.get("descriptiveStatistics")) if obj.get("descriptiveStatistics") is not None else None,
            "comparison": [ComparisonInner.from_dict(_item) for _item in obj.get("comparison")] if obj.get("comparison") is not None else None
        })
        return _obj


