# coding: utf-8

"""
    TBA III

    Diese API ermöglicht den Zugriff auf Auswertungsdaten von VERA. Sie bietet Endpunkte für die Abfrage von Leistungsdaten auf verschiedenen Ebenen (Lerngruppe, Schule, Bundesland) und für verschiedene Arten von Daten (Kompetenzstufen, Item-Statistiken, Aggregationen).

    The version of the OpenAPI document: 1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json




from pydantic import BaseModel, ConfigDict, Field, StrictFloat, StrictInt, StrictStr, field_validator
from typing import Any, ClassVar, Dict, List, Optional, Union
from api.models.competence_level import CompetenceLevel
try:
    from typing import Self
except ImportError:
    from typing_extensions import Self

class ItemParameters(BaseModel):
    """
    (importierte) Itemparameter aus den Itemkennwerten des IQB. Bisher unvollständige, exemplarische Liste.
    """ # noqa: E501
    logit: Optional[Union[StrictFloat, StrictInt]] = Field(default=None, description="Schwierigkeit des Items in Logit")
    bista_points: Optional[Union[StrictFloat, StrictInt]] = Field(default=None, description="Schwierigkeit des Items in Punkten nach deutscher Bildungsstandardmetrik", alias="bistaPoints")
    solution_frequency_gymnasium: Optional[Union[StrictFloat, StrictInt]] = Field(default=None, description="Mittlere Lösungshäufigkeit der Pilotierung an Gymnasien", alias="solutionFrequencyGymnasium")
    solution_frequency_non_gymnasium: Optional[Union[StrictFloat, StrictInt]] = Field(default=None, description="Mittlere Lösungshäufigkeit der Pilotierung an Nicht-Gymnasien", alias="solutionFrequencyNonGymnasium")
    solution_frequency_primary_school: Optional[Union[StrictFloat, StrictInt]] = Field(default=None, description="Mittlere Lösungshäufigkeit der Pilotierung an Grundschulen", alias="solutionFrequencyPrimarySchool")
    subject: Optional[StrictStr] = Field(default=None, description="Fach des Items")
    domain: Optional[StrictStr] = Field(default=None, description="Kompetenzbereich des Items")
    competence_level: Optional[CompetenceLevel] = Field(default=None, description="Kompetenzstufe des Items", alias="competenceLevel")
    cognitive_demand_level: Optional[StrictStr] = Field(default=None, description="Anforderungsbereich des Items", alias="cognitiveDemandLevel")
    general_mathematical_competence: Optional[List[StrictStr]] = Field(default=None, description="Allgemeine Kompetenz des Items", alias="generalMathematicalCompetence")
    core_idea: Optional[List[StrictStr]] = Field(default=None, description="Leitideen des Items", alias="coreIdea")
    competence_standard: Optional[List[StrictStr]] = Field(default=None, description="Liste der dem Item zugeordneten Kompetenzstandards", alias="competenceStandard")
    listening_or_reading_style: Optional[StrictStr] = Field(default=None, description="Hör- / Lesestil", alias="listeningOrReadingStyle")
    __properties: ClassVar[List[str]] = ["logit", "bistaPoints", "solutionFrequencyGymnasium", "solutionFrequencyNonGymnasium", "solutionFrequencyPrimarySchool", "subject", "domain", "competenceLevel", "cognitiveDemandLevel", "generalMathematicalCompetence", "coreIdea", "competenceStandard", "listeningOrReadingStyle"]

    @field_validator('listening_or_reading_style')
    def listening_or_reading_style_validate_enum(cls, value):
        """Validates the enum"""
        if value is None:
            return value

        if value not in ('selektiv', 'detailliert', 'inferierend', 'global',):
            raise ValueError("must be one of enum values ('selektiv', 'detailliert', 'inferierend', 'global')")
        return value

    model_config = {
        "populate_by_name": True,
        "validate_assignment": True,
        "protected_namespaces": (),
    }


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Create an instance of ItemParameters from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        _dict = self.model_dump(
            by_alias=True,
            exclude={
            },
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of competence_level
        if self.competence_level:
            _dict['competenceLevel'] = self.competence_level.to_dict()
        return _dict

    @classmethod
    def from_dict(cls, obj: Dict) -> Self:
        """Create an instance of ItemParameters from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "logit": obj.get("logit"),
            "bistaPoints": obj.get("bistaPoints"),
            "solutionFrequencyGymnasium": obj.get("solutionFrequencyGymnasium"),
            "solutionFrequencyNonGymnasium": obj.get("solutionFrequencyNonGymnasium"),
            "solutionFrequencyPrimarySchool": obj.get("solutionFrequencyPrimarySchool"),
            "subject": obj.get("subject"),
            "domain": obj.get("domain"),
            "competenceLevel": CompetenceLevel.from_dict(obj.get("competenceLevel")) if obj.get("competenceLevel") is not None else None,
            "cognitiveDemandLevel": obj.get("cognitiveDemandLevel"),
            "generalMathematicalCompetence": obj.get("generalMathematicalCompetence"),
            "coreIdea": obj.get("coreIdea"),
            "competenceStandard": obj.get("competenceStandard"),
            "listeningOrReadingStyle": obj.get("listeningOrReadingStyle")
        })
        return _obj


