# coding: utf-8

"""
    TBA III

    Diese API ermöglicht den Zugriff auf Auswertungsdaten von VERA. Sie bietet Endpunkte für die Abfrage von Leistungsdaten auf verschiedenen Ebenen (Lerngruppe, Schule, Bundesland) und für verschiedene Arten von Daten (Kompetenzstufen, Item-Statistiken, Aggregationen).

    The version of the OpenAPI document: 1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from fastapi import FastAPI

from api.apis.groups_api import router as GroupsApiRouter
from api.apis.schools_api import router as SchoolsApiRouter
from api.apis.states_api import router as StatesApiRouter

app = FastAPI(
    title="TBA III",
    description="Diese API ermöglicht den Zugriff auf Auswertungsdaten von VERA. Sie bietet Endpunkte für die Abfrage von Leistungsdaten auf verschiedenen Ebenen (Lerngruppe, Schule, Bundesland) und für verschiedene Arten von Daten (Kompetenzstufen, Item-Statistiken, Aggregationen).",
    version="1.0",
)

app.include_router(GroupsApiRouter)
app.include_router(SchoolsApiRouter)
app.include_router(StatesApiRouter)
