# coding: utf-8

"""
    TBA III

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.3
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from fastapi import FastAPI

from api.apis.groups_api import router as GroupsApiRouter
from api.apis.schools_api import router as SchoolsApiRouter
from api.apis.states_api import router as StatesApiRouter

app = FastAPI(
    title="TBA III",
    description="No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)",
    version="0.3",
)

app.include_router(GroupsApiRouter)
app.include_router(SchoolsApiRouter)
app.include_router(StatesApiRouter)
