openapi: '3.1.0'
info:
  title: TBA III
  summary: Schnittstelle für den Zugriff auf Auswertungsdaten von VERA
  version: '0.3'
  license:
    name: MIT
    url: https://opensource.org/license/MIT
tags:
  - name: groups
    description: Ergebnisse auf Ebene einer Lerngruppe
  - name: schools
    description: Ergebnisse zusammengefasst nach Schule
  - name: states
    description: Ergebnisse auf Landesebene
paths:
  /groups/{id}/competence-levels:
    $ref: 'paths/groups/competence-levels.yml'
  /groups/{id}/items:
    $ref: 'paths/groups/items.yml'
  /groups/{id}/aggregations:
    $ref: 'paths/groups/aggregations.yml'

  /schools/{id}/competence-levels:
    $ref: 'paths/schools/competence-levels.yml'
  /schools/{id}/items:
    $ref: 'paths/schools/items.yml'
  /schools/{id}/aggregations:
    $ref: 'paths/schools/aggregations.yml'
    
  /states/{id}/competence-levels:
    $ref: 'paths/states/competence-levels.yml'
  /states/{id}/items:
    $ref: 'paths/states/items.yml'
  /states/{id}/aggregations:
    $ref: 'paths/states/aggregations.yml'